# Generated by Django 3.1.4 on 2021-04-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.TextField(blank=True, db_column='device type', null=True)),
                ('operator', models.TextField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('success', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tests',
                'managed': False,
            },
        ),
    ]
