# Generated by Django 3.1.4 on 2021-04-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20210412_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
    ]
